[book]
title = "Caelix"
authors = ["Caelix contributors"]
language = "en"
src = "docs/src"

[build]
build-dir = "book"

[output.html]
site-url = "/caelix/"
git-repository-url = "https://github.com/Ohanronnie/caelix"
edit-url-template = "https://github.com/Ohanronnie/caelix/edit/main/{path}"
