[package]
name = "caelix-actix"
version = "0.0.37"
edition = "2024"
description = "Actix Web runtime adapter for Caelix."
license = "MIT"
repository = "https://github.com/Ohanronnie/caelix"
homepage = "https://ohanronnie.github.io/caelix/"
documentation = "https://docs.rs/caelix-actix"
readme = "README.md"

[features]
default = []
openapi = ["caelix-core/openapi"]
uploads = ["caelix-core/uploads"]

[dependencies]
actix-http = { workspace = true, default-features = false, features = ["ws"] }
actix-codec = "0.5.2"
actix-web = { version = "4.14.0", default-features = false, features = ["cookies", "macros", "ws"] }
bytes.workspace = true
bytestring.workspace = true
base64.workspace = true
caelix-core = { path = "../caelix-core", version = "0.0.37", default-features = false }
futures-util = { workspace = true, default-features = false, features = ["std", "sink"] }
futures-core.workspace = true
futures-sink.workspace = true
serde.workspace = true
serde_json.workspace = true
num_cpus.workspace = true
tokio = { workspace = true, default-features = false, features = ["sync"] }
tokio-util = { workspace = true, default-features = false, features = ["rt"] }
uuid = { workspace = true, features = ["v4"] }
[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync"] }
uuid = { workspace = true, features = ["serde", "v4"] }
tokio-tungstenite.workspace = true
