[package]
name = "caelix-axum"
version = "0.0.33"
edition = "2024"
description = "Axum runtime adapter for Caelix."
license = "MIT"
repository = "https://github.com/Ohanronnie/caelix"
homepage = "https://ohanronnie.github.io/caelix/"
documentation = "https://docs.rs/caelix-axum"
readme = "README.md"

[features]
default = []
socketio = ["dep:caelix-socketio"]
openapi = ["caelix-core/openapi"]
uploads = ["caelix-core/uploads"]

[dependencies]
axum = { workspace = true, features = ["ws"] }
bytes.workspace = true
caelix-core = { path = "../caelix-core", version = "0.0.33", default-features = false }
caelix-socketio = { path = "../caelix-socketio", version = "0.0.33", optional = true }
futures-util = { workspace = true, default-features = false, features = ["std", "sink"] }
http = "1.4.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "rt-multi-thread", "signal"] }
tower = { version = "0.5.3", features = ["util"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
http-body-util.workspace = true
tower = { version = "0.5.3", features = ["util"] }
tower-http = { workspace = true, features = ["compression-full", "trace"] }
