[package]
name = "caelix-macros"
version = "0.0.35"
edition = "2024"
description = "Procedural macros for the Caelix framework."
license = "MIT"
repository = "https://github.com/Ohanronnie/caelix"
homepage = "https://ohanronnie.github.io/caelix/"
documentation = "https://docs.rs/caelix-macros"
readme = "README.md"

[lib]
proc-macro = true

[features]
default = ["actix", "uploads"]
actix = []
axum = []
openapi = []
uploads = []
microservices = []
tokio = []
config = []

[dev-dependencies]
actix-web = "4.14.0"
caelix-actix = { path = "../caelix-actix", version = "0.0.35", features = ["uploads"] }
caelix-core = { path = "../caelix-core", version = "0.0.35", features = ["config", "uploads"] }
serde = { workspace = true, features = ["derive"] }
trybuild.workspace = true
validator = { version = "0.20", features = ["derive"] }

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
