#![deny(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]

//! Axum runtime adapter for Caelix applications.

mod application;
mod request_payload;
mod test_app;
mod websocket;

/// Re-exported for controller code generated by `caelix-macros`.
#[doc(hidden)]
pub use axum as __axum;
/// Re-exported for `#[caelix::main]` and `#[caelix::test]` under the Axum backend.
#[doc(hidden)]
pub use tokio as __tokio;

/// Re-exported public API.
pub use application::{
    Application, AxumRequestInfo, AxumRouterBuilder, DEFAULT_BODY_LIMIT_BYTES, to_axum_response,
};
/// Re-exported public API used by generated multipart controller wrappers.
#[doc(hidden)]
pub use request_payload::RequestPayload;
/// Re-exported public API.
pub use test_app::{TestApplication, TestApplicationBuilder, TestRequestBuilder, TestResponse};
/// Re-exported public API.
pub use websocket::DEFAULT_WEBSOCKET_MAX_MESSAGE_SIZE;
