//! Axum runtime adapter for Caelix applications.

mod application;
mod websocket;

/// Re-exported for controller code generated by `caelix-macros`.
#[doc(hidden)]
pub use axum as __axum;
/// Re-exported for `#[caelix::main]` and `#[caelix::test]` under the Axum backend.
#[doc(hidden)]
pub use tokio as __tokio;

pub use application::{
    Application, AxumRequestInfo, AxumRouterBuilder, DEFAULT_BODY_LIMIT_BYTES, to_axum_response,
};
pub use websocket::DEFAULT_WEBSOCKET_MAX_MESSAGE_SIZE;
