[package]
name = "caelix-microservices"
version = "0.0.36"
edition = "2024"
description = "NATS and Redis microservice transports for Caelix."
license = "MIT"
repository = "https://github.com/Ohanronnie/caelix"

[features]
default = ["nats"]
nats = []
redis = ["dep:redis"]

[dependencies]
async-nats.workspace = true
redis = { version = "1.4.1", optional = true, features = ["tokio-comp", "connection-manager", "streams"] }
caelix-core = { path = "../caelix-core", version = "0.0.36" }
futures-util = { workspace = true, default-features = false, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "signal", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
uuid = { workspace = true, features = ["v4"] }

[[example]]
name = "nestjs_redis_request_client"
required-features = ["redis"]
